In [27]:
import tensorflow as tf
import numpy as np

ph = tf.placeholder(shape=[None, 3], dtype=tf.int32)

# look the -1 in the first position
x = tf.slice(ph, [0, 0], [-1, 1])

input = np.array([[1,2,3],
                   [3,4,5],
                   [5,6,7],
                   [8,9,10]])
print(input.shape)

with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(sess.run(x, feed_dict={ph: input}))

(4, 3)
[[1]
 [3]
 [5]
 [8]]


In [31]:
x1 = np.array([[1, 2, 3],
               [3, 4, 5],
               [5, 6, 7]]).reshape(1, 3, 3, 1)
x2 = x1
concat = tf.concat([x1, x2], 3)

with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        ret = sess.run(concat, feed_dict={ph: input})
        print(ret.shape)
        print(ret)

(1, 3, 3, 2)
[[[[1 1]
   [2 2]
   [3 3]]

  [[3 3]
   [4 4]
   [5 5]]

  [[5 5]
   [6 6]
   [7 7]]]]


In [38]:
x = tf.placeholder("float", shape=[None, None, None, 1])
nx = tf.shape(x)[1]
ny = tf.shape(x)[2]
x_image = tf.reshape(x, tf.stack([-1, nx, ny, 1]))
print(tf.shape(x_image))
print(x1)
print(x1.shape)
with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        ret = sess.run(x_image, feed_dict={x: x1})
        print(ret.shape)
        print(ret)

Tensor("Shape_17:0", shape=(4,), dtype=int32)
[[[[1]
   [2]
   [3]]

  [[3]
   [4]
   [5]]

  [[5]
   [6]
   [7]]]]
(1, 3, 3, 1)
(1, 3, 3, 1)
[[[[1.]
   [2.]
   [3.]]

  [[3.]
   [4.]
   [5.]]

  [[5.]
   [6.]
   [7.]]]]
